# Generated by Django 4.2.7 on 2026-05-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节目名称')),
                ('host', models.CharField(max_length=50, verbose_name='主持人')),
                ('category', models.CharField(choices=[('music', '音乐类'), ('news', '新闻类'), ('talk', '访谈类'), ('story', '故事类'), ('education', '教育类'), ('entertainment', '娱乐类'), ('other', '其他')], max_length=20, verbose_name='节目类型')),
                ('description', models.TextField(verbose_name='节目简介')),
                ('duration', models.IntegerField(verbose_name='节目时长(分钟)')),
                ('status', models.CharField(choices=[('active', '播出中'), ('inactive', '停播'), ('pending', '待审核')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '广播节目',
                'verbose_name_plural': '广播节目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('submitter_name', models.CharField(max_length=50, verbose_name='投稿人姓名')),
                ('submitter_class', models.CharField(blank=True, max_length=50, verbose_name='投稿人班级')),
                ('submission_type', models.CharField(choices=[('song', '歌曲点播'), ('article', '文章投稿'), ('story', '故事投稿'), ('blessing', '祝福语'), ('other', '其他')], max_length=20, verbose_name='投稿类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('broadcast', '已播出')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_remark', models.TextField(blank=True, verbose_name='审核备注')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '投稿信息',
                'verbose_name_plural': '投稿信息',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='节目')),
            ],
            options={
                'verbose_name': '播放排班',
                'verbose_name_plural': '播放排班',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField(verbose_name='播放日期')),
                ('start_time', models.TimeField(verbose_name='实际开始时间')),
                ('end_time', models.TimeField(verbose_name='实际结束时间')),
                ('host', models.CharField(max_length=50, verbose_name='实际主持人')),
                ('listeners_count', models.IntegerField(default=0, verbose_name='听众人数')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program', verbose_name='节目')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.schedule', verbose_name='对应排班')),
            ],
            options={
                'verbose_name': '播放记录',
                'verbose_name_plural': '播放记录',
                'ordering': ['-play_date', '-start_time'],
            },
        ),
    ]
