appname = farmhouse-order-system
httpport = 8080
runmode = dev
autorender = true
viewspath = views

mysqluser = root
mysqlpass = 123456
mysqlhost = 127.0.0.1
mysqlport = 3306
mysqldb = farmhouse_order

sessionon = true
sessionprovider = file
sessionproviderconfig = ./tmp
sessionname = farmhouse-session
sessiongcmaxlifetime = 3600
sessionmaxlifetime = 3600
