# Generated by Django 5.0.14 on 2026-05-27 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='行为名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='行为代码')),
                ('description', models.TextField(verbose_name='行为描述')),
                ('is_negative', models.BooleanField(default=False, verbose_name='是否不良行为')),
                ('severity_level', models.IntegerField(default=1, verbose_name='严重程度')),
            ],
            options={
                'verbose_name': '行为类型',
                'verbose_name_plural': '行为类型',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宠物名称')),
                ('species', models.CharField(max_length=50, verbose_name='物种')),
                ('breed', models.CharField(max_length=100, verbose_name='品种')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('weight', models.FloatField(verbose_name='体重(kg)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='方案标题')),
                ('description', models.TextField(verbose_name='方案描述')),
                ('duration_days', models.IntegerField(default=30, verbose_name='持续天数')),
                ('difficulty_level', models.CharField(default='medium', max_length=20, verbose_name='难度等级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='api.pet', verbose_name='宠物')),
                ('target_behaviors', models.ManyToManyField(to='api.behaviortype', verbose_name='目标行为')),
            ],
            options={
                'verbose_name': '训练方案',
                'verbose_name_plural': '训练方案',
            },
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='步骤顺序')),
                ('title', models.CharField(max_length=200, verbose_name='步骤标题')),
                ('instruction', models.TextField(verbose_name='操作说明')),
                ('expected_duration', models.IntegerField(default=5, verbose_name='预计时长(分钟)')),
                ('tips', models.TextField(blank=True, verbose_name='小贴士')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.trainingplan', verbose_name='训练方案')),
            ],
            options={
                'verbose_name': '训练步骤',
                'verbose_name_plural': '训练步骤',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='完成日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('success_rate', models.FloatField(default=0, verbose_name='成功率')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.trainingplan', verbose_name='训练方案')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainingstep', verbose_name='训练步骤')),
            ],
            options={
                'verbose_name': '训练进度',
                'verbose_name_plural': '训练进度',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('minio_object_name', models.CharField(max_length=255, verbose_name='MinIO对象名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('duration', models.FloatField(default=0, verbose_name='时长(秒)')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='处理状态')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '视频上传',
                'verbose_name_plural': '视频上传',
            },
        ),
        migrations.CreateModel(
            name='BehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('start_time', models.FloatField(verbose_name='开始时间(秒)')),
                ('end_time', models.FloatField(verbose_name='结束时间(秒)')),
                ('frame_count', models.IntegerField(default=0, verbose_name='帧数')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分析时间')),
                ('behavior_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.behaviortype', verbose_name='行为类型')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.videoupload', verbose_name='视频')),
            ],
            options={
                'verbose_name': '行为分析',
                'verbose_name_plural': '行为分析',
            },
        ),
    ]
