# Generated by Django 6.0.5 on 2026-05-27 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_disease', models.CharField(max_length=50, verbose_name='主要诊断')),
                ('top_disease_name', models.CharField(max_length=100, verbose_name='主要诊断名称')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('severity_level', models.CharField(max_length=20, verbose_name='严重程度')),
                ('severity_color', models.CharField(max_length=20, verbose_name='严重程度颜色')),
                ('ai_report', models.TextField(verbose_name='AI诊断报告')),
                ('recommendations', models.TextField(verbose_name='治疗建议')),
                ('doctor_reviewed', models.BooleanField(default=False, verbose_name='医生已审核')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='诊断时间')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical_records.medicalimage', verbose_name='影像')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnosis', to='medical_records.medicalrecord', verbose_name='医疗记录')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='审核医生')),
            ],
            options={
                'verbose_name': '诊断结果',
                'verbose_name_plural': '诊断结果',
                'db_table': 'diagnosis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, verbose_name='病症代码')),
                ('disease_name', models.CharField(max_length=100, verbose_name='病症名称')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('description', models.TextField(verbose_name='病症描述')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ai_diagnosis.diagnosisresult', verbose_name='诊断结果')),
            ],
            options={
                'verbose_name': '病症预测',
                'verbose_name_plural': '病症预测',
                'db_table': 'disease_predictions',
            },
        ),
    ]
