# Generated by Django 5.2.14 on 2026-05-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('checkin', '签到'), ('share', '分享'), ('consume', '消费')], max_length=20, verbose_name='任务类型')),
                ('points_reward', models.IntegerField(default=0, verbose_name='积分奖励')),
                ('growth_reward', models.IntegerField(default=0, verbose_name='成长值奖励')),
                ('condition', models.JSONField(default=dict, verbose_name='任务条件')),
            ],
            options={
                'verbose_name': '会员任务',
                'verbose_name_plural': '会员任务',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='会员等级')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('growth_value', models.IntegerField(default=0, verbose_name='成长值')),
                ('invite_code', models.CharField(max_length=20, unique=True, verbose_name='邀请码')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='members.memberprofile', verbose_name='邀请人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员档案',
                'verbose_name_plural': '会员档案',
            },
        ),
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(max_length=50, verbose_name='分享类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分享码')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('convert_count', models.IntegerField(default=0, verbose_name='转化次数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分享记录',
                'verbose_name_plural': '分享记录',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('browse', '浏览'), ('favorite', '收藏'), ('purchase', '购买')], max_length=20, verbose_name='行为类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='签到日期')),
                ('points_earned', models.IntegerField(default=10, verbose_name='获得积分')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'unique_together': {('user', 'check_date')},
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='members.membertask', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户任务',
                'verbose_name_plural': '用户任务',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
