# Generated by Django 6.0.5 on 2026-05-27 04:10

import django.core.files.storage
import django.db.models.deletion
import medical_records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='诊断标题')),
                ('symptoms', models.TextField(verbose_name='症状描述')),
                ('status', models.CharField(choices=[('pending', '待诊断'), ('diagnosed', '已诊断'), ('confirmed', '已确认'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='医生诊断')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='治疗方案')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='就诊日期')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '医疗记录',
                'verbose_name_plural': '医疗记录',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('xray', 'X光片'), ('ct', 'CT扫描'), ('mri', '核磁共振'), ('ultrasound', '超声波'), ('other', '其他')], default='xray', max_length=20, verbose_name='影像类型')),
                ('encrypted_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='F:\\TraeProject\\dogFood6\\Project16\\media\\encrypted'), upload_to=medical_records.models.encrypted_upload_path, verbose_name='加密影像文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='是否加密')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medical_records.medicalrecord', verbose_name='医疗记录')),
            ],
            options={
                'verbose_name': '医疗影像',
                'verbose_name_plural': '医疗影像',
                'db_table': 'medical_images',
            },
        ),
    ]
