# Generated by Django 6.0.5 on 2026-05-27 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='宠物名称')),
                ('species', models.CharField(choices=[('dog', '狗'), ('cat', '猫'), ('bird', '鸟'), ('rabbit', '兔子'), ('other', '其他')], max_length=20, verbose_name='物种')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='品种')),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄（月')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重（kg）')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='毛色')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'db_table': 'pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
