# Generated by Django 5.2.14 on 2026-05-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('config_schema', models.JSONField(default=dict, verbose_name='配置方案')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_templates', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '定制模板',
                'verbose_name_plural': '定制模板',
            },
        ),
        migrations.CreateModel(
            name='CustomizeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_data', models.JSONField(default=dict, verbose_name='配置数据')),
                ('preview_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='预览地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customize_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customize.customizetemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '定制订单',
                'verbose_name_plural': '定制订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
