FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o nursery-management .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/nursery-management .
COPY --from=builder /app/web ./web

EXPOSE 8080

CMD ["./nursery-management"]
