@echo off
echo Installing dependencies...
pip install -r requirements.txt

echo Applying database migrations...
python manage.py makemigrations
python manage.py migrate

echo Initializing sample data...
python manage.py init_data

echo Creating superuser...
python create_superuser.py

echo Starting server...
python manage.py runserver 0.0.0.0:8000
