# Generated by Django 5.2.14 on 2026-05-31 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('campaign_type', models.CharField(choices=[('flash_sale', '限时优惠'), ('new_arrival', '新品首发'), ('group_buy', '拼团')], max_length=20, verbose_name='活动类型')),
                ('rules', models.JSONField(default=dict, verbose_name='活动规则')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '营销活动',
                'verbose_name_plural': '营销活动',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('coupon_type', models.CharField(choices=[('full_reduction', '满减'), ('discount', '折扣'), ('free_shipping', '免邮')], max_length=20, verbose_name='优惠券类型')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='优惠金额/折扣率')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费金额')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='拼团价')),
                ('target_count', models.IntegerField(verbose_name='目标人数')),
                ('current_count', models.IntegerField(default=0, verbose_name='当前人数')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to='campaigns.campaign', verbose_name='活动')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buys', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '拼团活动',
                'verbose_name_plural': '拼团活动',
            },
        ),
        migrations.CreateModel(
            name='GroupBuyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False, verbose_name='是否团长')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.groupbuy', verbose_name='拼团')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_buy_participations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '拼团参与',
                'verbose_name_plural': '拼团参与',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='campaigns.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
            },
        ),
    ]
